CONFIG_DISK_ACCESS=y
CONFIG_LOG=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=2560
CONFIG_HEAP_MEM_POOL_SIZE=2560

CONFIG_SHELL=y
CONFIG_FILE_SYSTEM_SHELL=y

CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_SD_LOG_LEVEL_DBG=y

CONFIG_STACK_CANARIES=y
CONFIG_STACK_SENTINEL=y
